env:
  type: "pong"
  gamma: 0.99
  history: 4

eps:
  start: 1
  end: 0.01
  steps: 1_000_000
  schedule: "linear"

buffer:
  method: "random"
  options:
    base:
      size: 100_000
    random: {}
    priority:
      alpha: 0.5
      beta: 0.4
      prio_type: "proportional"

train:
  max_steps: 10_000_000
  start_step: 100_000
  
  batch_size: 32
  max_grad_norm: 10
  update_freq: 4
  grad_steps: 1
  target_update_steps: 1_000
  
  lr: 0.0001

net:
  ddqn: true

log:
  path: run_tracking
  run: test_abc_buffer_1

eval:
  frequency: 50_000
  noop_max: 30
  n_episodes: 10
  ep_max_frames: 18_000
  eps: 0.01
