env:
  type: "pong"
  gamma: 0.99
  history: 4

eps:
  start: 1
  end: 0.01
  steps: 1_000_000
  schedule: "linear"

buffer:
  size: 100_000
  method: "random"

train:
  max_steps: 10_000_000
  start_step: 100_000
  
  batch_size: 32
  max_grad_norm: 10
  update_freq: 4
  grad_steps: 1
  target_update_steps: 1_000
  
  lr: 0.0001